params: implement ECIP-1078/1079 feature activation
etclabscore/multi-geth-fork pull request #128
Opened 2020-01-29 19:14 UTC by meowsbits

> - https://github.com/ethereumclassic/ECIPs/pull/263/files?short_path=d39459a#diff-d39459a451d1f1cf1bb1d6b1fddcb4f0
> - https://github.com/ethereumclassic/ECIPs/pull/261/files#diff-f331ca50d292642838a6be87214ac1e7

Implements 'Phoenix' aka 'Aztlan Fix' fork specification
which is described as a 'simultaneous' fork adjacent
to the fork specified in ECIP-1061 and ECIP-1072.

The intention is to sidestep potential vulnerabilities
related to gas costs.

Signed-off-by: meows <b5c6@protonmail.com>

2020-01-31 15:57 UTC, soc1c commented
FYI https://github.com/ethereumclassic/ECIPs/issues/284

2020-01-31 16:07 UTC, soc1c reviewed
We need to explicitly disable EIP 2200. On Mordor it already triggered and on Kotti it will soon. For mainnet, we will decide next week.

2020-01-31 16:07 UTC, soc1c commented on params/config_mordor.go
> +		//EIP2200FBlock: big.NewInt(778507), // RePetersburg (== re-1283)
this won't work for mordor anymore.

2020-02-03 10:25 UTC, soc1c commented
proposed block numbers for phoenix/ecip-1078
- `976_231` on Mordor Classic PoW-testnet (March 4th, 2020)
- `2_208_203` on Kotti Classic PoA-testnet (March 11th, 2020)
- `10_500_839` on Ethereum Classic PoW-mainnet (March 25th, 2020)

ref https://github.com/ethereumclassic/ECIPs/pull/285

2020-02-03 10:26 UTC, soc1c requested changes
- needs to disable eip-2200 on mordor and kotti
- needs to update block numbers for phoenix/ecip-1078

2020-02-03 15:26 UTC, meowsbits commented
@soc1c Thanks for review. I need to merge some stuff first, but then will address these things soon!

2020-02-05 12:07 UTC, soc1c commented on params/config_kotti.go
> -		EIP1884FBlock: nil,
can we keep this line just for the sake of readability? I know it does not solve anything.kk

2020-02-05 12:08 UTC, soc1c commented on params/config_classic.go
> +		//EIP2200FBlock: big.NewInt(10500839), // RePetersburg (=~ re-1283)
can we have enable and disable on the same block number to be super correct and improve readability? I know it wouldn't change anything.

2020-02-05 12:10 UTC, soc1c approved these changes
logic looks good to me. left two comments for cosmetic improvements.

2020-02-05 12:24 UTC, meowsbits commented on params/config_kotti.go
> -		EIP1884FBlock: nil,
https://github.com/etclabscore/multi-geth/pull/128/commits/26b180edc4edb435ee8f68c08b118329dcdf87e9

2020-02-05 12:24 UTC, meowsbits commented on params/config_classic.go
> +		//EIP2200FBlock: big.NewInt(10500839), // RePetersburg (=~ re-1283)
https://github.com/etclabscore/multi-geth/pull/128/commits/26b180edc4edb435ee8f68c08b118329dcdf87e9

2020-02-06 11:56 UTC, merged

2020-02-10 14:41 UTC, tzdybal reviewed
Better late than never - LGTM