Merge multi-geth/multi-geth master
etclabscore/multi-geth-fork pull request #54
Opened 2019-11-15 10:53 UTC by meowsbits

This merges the later 'sidestream' developments from multi-geth/multi-geth.

2019-11-21 11:19 UTC, tzdybal requested changes
Too huge to be thorough.

2019-11-21 11:19 UTC, tzdybal commented on .github/FUNDING.yml
> +github: sorpaas
With all due respect, I think we shouldn't merge this.

2019-11-21 13:17 UTC, meowsbits commented on .github/FUNDING.yml
> +github: sorpaas
Fixed w https://github.com/etclabscore/multi-geth/pull/54/commits/49faa47dc2cd1f6526b40576ba965e6963cedef7

2019-11-22 08:05 UTC, tzdybal approved these changes

2019-11-22 11:22 UTC, merged