Feat/x chainspec types and tests configurator impl
etclabscore/multi-geth-fork pull request #70
Opened 2019-11-27 16:22 UTC by meowsbits

Implementing the `Configurator` interface(s).

Very WIP.

2019-11-27 16:24 UTC, meowsbits commented
One last big bite is to refactor tests/ config settings.

2019-11-28 15:02 UTC, meowsbits commented
Tests passing now.

Still a few things left TODO.

2019-11-28 15:05 UTC, meowsbits commented
Note that I've removed support for Musicoin.

There were complexities that were not worth adapting and working around. I was the one who added Musicoin support, for fun, and it has not been maintained nor actively supported by anyone from that space.

2019-12-06 16:35 UTC, meowsbits commented on cmd/geth/chaincmd.go
> +	dumpGenesisCommand = cli.Command{
This additional command isn't necessary; it was just a convenient tool for development and sanity testing.

 It feature-duplicates #39 , and so should probably be removed as separate concern.

2019-12-07 13:33 UTC, meowsbits commented on cmd/geth/chaincmd.go
> +	dumpGenesisCommand = cli.Command{
Resolved with https://github.com/etclabscore/multi-geth/pull/70/commits/991e283d554d38aa90104ba0ac30784006f634e9

2019-12-09 21:56 UTC, tzdybal requested changes
I"m requesting changes, because there are some obsolete files in changeset.
There are also some other issues in multiple files, like:
 - missing license headers (I'll create new issue related to licensing issues (full review + maybe some automatic tools, etc))
 - large blocks of commented out obsolete code (pointed in some individual comments, but not all)

2019-12-09 21:56 UTC, tzdybal commented on cmd/faucet/faucet.go
> +	common2 "github.com/ethereum/go-ethereum/params/types/common"
I'm not a big fan of `common2` alias. Maybe something like: `ctypes` (C++ style FTW)?

2019-12-09 21:56 UTC, tzdybal commented on core/forkid/forkid_test.go
> +			[]uint64{1150000, 2500000, 3000000, 5000000, 5900000, 8772000},
Hell yeah, ETC is not a fork!

2019-12-09 21:56 UTC, tzdybal commented on core/vm/jump_table.go
> +	"github.com/ethereum/go-ethereum/params/types/common"
Maybe we can think about different name for `types/common` so it can have same name/alias in all files?

2019-12-09 21:56 UTC, tzdybal commented on eth/backend.go
> +		if p, ok := chainConfig.(*paramtypes.MultiGethChainConfig); ok {
Why `chainConfig` here is not a `ChainConfigurator` with getter for `TrustedCheckpoint`?

2019-12-09 21:56 UTC, tzdybal commented on eth/handler.go
> +	Genesis    common.Hash               `json:"genesis"`    // SHA3 hash of the host's genesis block
Looks like we need to run `gofmt` on this file.

2019-12-09 21:56 UTC, tzdybal commented on params/types/gen_genesis_patch.diff
> +diff --git a/params/types/gen_genesis.go b/params/types/gen_genesis.go
This seems like a file inclusion by mistake.

2019-12-09 21:56 UTC, tzdybal commented on params/types/common/configurator_iface.go
> +package common
Missing license file header.

2019-12-09 21:56 UTC, tzdybal commented on params/types/common/configurator.go
>  package common
Missing license file header.

2019-12-09 21:56 UTC, tzdybal commented on params/types/chain_config.go
> +//
Probably we should just remove those comments before merge.

2019-12-09 21:56 UTC, tzdybal commented on params/parity.json.d/transition_test.json
> +		"0000000000000000000000000000000000000005": { "builtin": { "name": "modexp", "activate_at": "0x5", "pricing": { "modexp": { "divisor": 20 } } } },
Why `"balance": "1",` is not present in this line?

2019-12-09 21:56 UTC, tzdybal commented on cmd/geth/retesteth.go
> +			header.Extra = common.CopyBytes(vars.DAOForkBlockExtra)
This looks like a change of logic, not only refactoring. Am I missing something? Why `Extra` is always set?

2019-12-09 21:56 UTC, tzdybal commented on consensus/misc/dao.go
> +	if daoForkBlock == nil && !convert.AsGenericCC(config).DAOSupport() {
This can also result in  `fatal`. I get the idea that getters (like `DAOSupport`) only return value in "normal" CC, but maybe for `GenericCC` we should just throw `error`, instead of calling `fatal`?

2019-12-09 21:56 UTC, tzdybal commented on consensus/misc/dao.go
> +	if convert.AsGenericCC(config).DAOSupport() {
This check is unnecessary (because of lines: 54-55).

2019-12-09 21:56 UTC, tzdybal commented on core/genesis_test.go
> +package core
No license boilerplate.

2019-12-09 21:56 UTC, tzdybal commented on params/convert/generic.go
> +	panic(fmt.Sprintf("uimplemented DAO logic, config: %v", c.ChainConfigurator))
Maybe just return error?

2019-12-16 16:40 UTC, meowsbits commented on eth/backend.go
> +		if p, ok := chainConfig.(*paramtypes.MultiGethChainConfig); ok {
Because `GetTrustedCheckPoint` is not yet installed as an interface method.

2019-12-16 17:02 UTC, meowsbits commented
Thanks for feedback @tzdybal . Will resolve reviews via PRs against #82, which essentially renames/repatterns this change set to us a broader "development branch" strategy for the (big) task at hand.

Once I've resolved all reviews here, I'll close this PR in favor of the bespoke development change set.

2019-12-16 17:15 UTC, meowsbits commented
@tzdybal 
> missing license headers (I'll create new issue related to licensing issues (full review + maybe some automatic tools, etc))
Resolved with https://github.com/etclabscore/multi-geth/pull/84

2019-12-16 17:37 UTC, meowsbits commented on core/vm/jump_table.go
> +	"github.com/ethereum/go-ethereum/params/types/common"
https://github.com/etclabscore/multi-geth/pull/85

2019-12-16 17:37 UTC, meowsbits commented on cmd/faucet/faucet.go
> +	common2 "github.com/ethereum/go-ethereum/params/types/common"
https://github.com/etclabscore/multi-geth/pull/85

2019-12-16 17:40 UTC, meowsbits commented on eth/handler.go
> +	Genesis    common.Hash               `json:"genesis"`    // SHA3 hash of the host's genesis block
https://github.com/etclabscore/multi-geth/pull/86

2019-12-16 17:42 UTC, meowsbits commented on params/types/common/configurator_iface.go
> +package common
#84

2019-12-16 17:42 UTC, meowsbits commented on params/types/common/configurator.go
>  package common
#84

2019-12-16 17:56 UTC, meowsbits commented on params/types/gen_genesis_patch.diff
> +diff --git a/params/types/gen_genesis.go b/params/types/gen_genesis.go
I actually included this on purpose. Since the file `gen_genesis.go` is a generated file (although whether that really matters is arguable and IMO not really that important in this case), I included a patch file with the diff, so that you can use this file with `git apply` and programmatically modify the generated version.

Ugly, yes.

Maybe we should just add a README.md with instructions for file generation/modification in case it's ever useful again, and remove the `GENERATED FILE` warning comments in the gen_* files here. The file generation is in this case IMO a one-off convenience, and should only ever be used in ad hoc development circumstances; it is not used in the CI and doesn't handle dynamic content at all.

2019-12-16 17:57 UTC, meowsbits commented on params/parity.json.d/transition_test.json
> +		"0000000000000000000000000000000000000005": { "builtin": { "name": "modexp", "activate_at": "0x5", "pricing": { "modexp": { "divisor": 20 } } } },
I think that's a question for upstream at paritytech/parity-ethereum.

2019-12-16 17:58 UTC, meowsbits commented on core/genesis_test.go
> +package core
#84

2019-12-16 17:59 UTC, meowsbits commented on core/forkid/forkid_test.go
> +			[]uint64{1150000, 2500000, 3000000, 5000000, 5900000, 8772000},
Rel https://github.com/etclabscore/multi-geth/pull/82#discussion_r358360780

2019-12-16 18:08 UTC, meowsbits commented on params/types/gen_genesis_patch.diff
> +diff --git a/params/types/gen_genesis.go b/params/types/gen_genesis.go
https://github.com/etclabscore/multi-geth/pull/82/files?file-filters%5B%5D=.diff#r358383794

2019-12-16 18:55 UTC, meowsbits commented on cmd/geth/retesteth.go
> +			header.Extra = common.CopyBytes(vars.DAOForkBlockExtra)
https://github.com/etclabscore/multi-geth/pull/88

I think this was resolved anyways, but the PR fixes an additional issue as well.

2019-12-16 18:58 UTC, meowsbits commented on params/types/chain_config.go
> +//
Is resolved at #82

2019-12-16 19:15 UTC, meowsbits commented on params/convert/generic.go
> +	panic(fmt.Sprintf("uimplemented DAO logic, config: %v", c.ChainConfigurator))
I'm `panic`ing here because this is necessary logic for the data types, similar to a default for interface implementation generation:

```go
// Less ...
// Swap ...
func (c *ChainConfig) Len() int {
    panic("implement me")
}
```

Since this method isn't an `type ChainConfigurator interface` method, we need to be totally certain that the logic is implemented at the "generic interface" level.

For a config data type that is DAO agnostic (ie never intended for a "canonical" chain), then it will be enough to do

```go
if _, ok := c.ChainConfigurator.(*MyDataType); ok { return false }
```

Does that make sense?

2019-12-16 19:48 UTC, meowsbits commented on consensus/misc/dao.go
> +	if convert.AsGenericCC(config).DAOSupport() {
@tzdybal In regard to these three DAO-related comments; these are interdependent logics and possible changes; can you please, if you want to pursue these ideas, make a PR against the `etclabscore-develop` branch to propose changes as you see fit? Would love to see what you may have in mind :) :+1:

2019-12-16 19:49 UTC, meowsbits commented on params/convert/generic.go
> +	panic(fmt.Sprintf("uimplemented DAO logic, config: %v", c.ChainConfigurator))
And/or see comment above about proposing alternative :heavy_check_mark:

2019-12-16 20:10 UTC, meowsbits commented
@tzdybal Once you've seen and __if you're OK with these resolutions and proposed `development` branch plan__, please go ahead and close this PR and we'll shift focus to working based on #82.

Otherwise, just say so and we'll figure something else out.

2019-12-17 22:31 UTC, closed without merging