Feat/packages refactor
etclabscore/multi-geth-fork pull request #91
Opened 2019-12-20 01:02 UTC by meowsbits

Refactors `params` package structure.

Consolidates `params/convert` and `params/types/configurator*` to keep similar logic in same package, eg `configurator.Convert` and `configurator.Compare` and `configurator.Transitions`, `IsValid`, etc.

Of the `Configurator` idea, only the actual `type Configurator interface` is left in `params/types/ctypes/configurator_iface.go`.

__Old__:
```
$ tree -I parity.json.d params
params
├── alloc_ethersocial.go
├── alloc.go
├── alloc_kotti.go
├── alloc_mix.go
├── alloc_social.go
├── bootnodes_classic.go
├── bootnodes_ethersocial.go
├── bootnodes.go
├── bootnodes_kotti.go
├── bootnodes_mix.go
├── bootnodes_mordor.go
├── bootnodes_social.go
├── config_classic.go
├── config_ethersocial.go
├── config.go
├── config_kotti.go
├── config_mix.go
├── config_mordor.go
├── config_social.go
├── config_test.go
├── convert
│   ├── aleth.go
│   ├── aleth_test.go
│   ├── convert.go
│   ├── convert_test.go
│   ├── generic.go
│   ├── json.go
│   ├── parity.go
│   ├── parity_test.go
│   ├── pyethereum.go
│   └── testdata
│       ├── stureby_aleth.json
│       ├── stureby_geth.json
│       └── stureby_parity.json
├── genesis_classic.go
├── genesis_ethersocial.go
├── genesis.go
├── genesis_kotti.go
├── genesis_mix.go
├── genesis_mordor.go
├── genesis_social.go
├── mkalloc.go
├── types
│   ├── aleth
│   │   └── aleth.go
│   ├── chain_config_configurator.go
│   ├── chain_config.go
│   ├── chain_config_test.go
│   ├── ctypes
│   │   ├── configurator.go
│   │   ├── configurator_iface.go
│   │   ├── configurator_test.go
│   │   ├── ethash_reward.go
│   │   ├── types.go
│   │   └── types_test.go
│   ├── genesis.go
│   ├── gen_genesis_account.go
│   ├── gen_genesis.go
│   ├── goethereum
│   │   ├── goethereum_configurator.go
│   │   └── goethereum.go
│   ├── parity
│   │   ├── parity_configurator.go
│   │   ├── parity_configurator_test.go
│   │   ├── parity.go
│   │   └── parity_test.go
│   ├── pyethereum
│   │   └── pyethereum.go
│   └── README.md
├── vars
│   ├── dao.go
│   ├── denomination.go
│   ├── network_params.go
│   └── protocol_params.go
└── version.go

```

__New:__
```
params
├── alloc_ethersocial.go
├── alloc.go
├── alloc_kotti.go
├── alloc_mix.go
├── alloc_social.go
├── bootnodes_classic.go
├── bootnodes_ethersocial.go
├── bootnodes.go
├── bootnodes_kotti.go
├── bootnodes_mix.go
├── bootnodes_mordor.go
├── bootnodes_social.go
├── config_classic.go
├── config_ethersocial.go
├── config.go
├── config_kotti.go
├── config_mix.go
├── config_mordor.go
├── config_social.go
├── config_test.go
├── confp
│   ├── configurator.go
│   ├── configurator_test.go
│   ├── convert.go
│   ├── generic
│   │   ├── doc.go
│   │   └── generic.go
│   ├── internal
│   │   ├── convert_test.go
│   │   ├── doc_test.go
│   │   ├── parity_test.go
│   │   └── testdata
│   │       ├── stureby_aleth.json
│   │       ├── stureby_geth.json
│   │       └── stureby_parity.json
│   └── tconvert
│       ├── aleth.go
│       ├── aleth_test.go
│       ├── doc.go
│       ├── parity.go
│       └── pyethereum.go
├── genesis_classic.go
├── genesis_ethersocial.go
├── genesis.go
├── genesis_kotti.go
├── genesis_mix.go
├── genesis_mordor.go
├── genesis_social.go
├── mkalloc.go
├── types
│   ├── aleth
│   │   └── aleth.go
│   ├── ctypes
│   │   ├── configurator_iface.go
│   │   ├── ethash_reward.go
│   │   ├── types.go
│   │   └── types_test.go
│   ├── genesis.go
│   ├── gen_genesis_account.go
│   ├── gen_genesis.go
│   ├── goethereum
│   │   ├── goethererum_configurator_test.go
│   │   ├── goethereum_configurator.go
│   │   └── goethereum.go
│   ├── internal
│   │   └── vars_configurator.go
│   ├── multigeth
│   │   ├── chain_config_configurator.go
│   │   ├── chain_config.go
│   │   └── chain_config_test.go
│   ├── parity
│   │   ├── parity_configurator.go
│   │   ├── parity_configurator_test.go
│   │   ├── parity.go
│   │   └── parity_test.go
│   ├── pyethereum
│   │   └── pyethereum.go
│   └── README.md
├── vars
│   ├── dao.go
│   ├── denomination.go
│   ├── network_params.go
│   └── protocol_params.go
└── version.go

14 directories, 70 files

```

__Diff:__
```
1,5c1,5
< params               
< ├── alloc_ethersocial.go  
< ├── alloc.go      
< ├── alloc_kotti.go       
< ├── alloc_mix.go 
---
> params
> ├── alloc_ethersocial.go
> ├── alloc.go
> ├── alloc_kotti.go
> ├── alloc_mix.go
9,10c9,10
< ├── bootnodes.go         
< ├── bootnodes_kotti.go    
---
> ├── bootnodes.go
> ├── bootnodes_kotti.go
14c14
< ├── config_classic.go                                                                             
---
> ├── config_classic.go
16,18c16,18
< ├── config.go                              
< ├── config_kotti.go                                                  
< ├── config_mix.go             
---
> ├── config.go
> ├── config_kotti.go
> ├── config_mix.go
20c20
< ├── config_social.go    
---
> ├── config_social.go
22,35c22,42
< ├── convert       
< │   ├── aleth.go
< │   ├── aleth_test.go
< │   ├── convert.go      
< │   ├── convert_test.go     
< │   ├── generic.go
< │   ├── json.go       
< │   ├── parity.go   
< │   ├── parity_test.go 
< │   ├── pyethereum.go  
< │   └── testdata     
< │       ├── stureby_aleth.json
< │       ├── stureby_geth.json
< │       └── stureby_parity.json
---
> ├── confp
> │   ├── configurator.go
> │   ├── configurator_test.go
> │   ├── convert.go
> │   ├── generic
> │   │   ├── doc.go
> │   │   └── generic.go
> │   ├── internal
> │   │   ├── convert_test.go
> │   │   ├── doc_test.go
> │   │   ├── parity_test.go
> │   │   └── testdata
> │   │       ├── stureby_aleth.json
> │   │       ├── stureby_geth.json
> │   │       └── stureby_parity.json
> │   └── tconvert
> │       ├── aleth.go
> │       ├── aleth_test.go
> │       ├── doc.go
> │       ├── parity.go
> │       └── pyethereum.go
38c45
< ├── genesis.go      
---
> ├── genesis.go
41,54c48,56
< ├── genesis_mordor.go  
< ├── genesis_social.go       
< ├── mkalloc.go    
< ├── types      
< │   ├── aleth     
< │   │   └── aleth.go  
< │   ├── chain_config_configurator.go
< │   ├── chain_config.go    
< │   ├── chain_config_test.go
< │   ├── ctypes            
< │   │   ├── configurator.go
< │   │   ├── configurator_iface.go 
< │   │   ├── configurator_test.go 
< │   │   ├── ethash_reward.go       
---
> ├── genesis_mordor.go
> ├── genesis_social.go
> ├── mkalloc.go
> ├── types
> │   ├── aleth
> │   │   └── aleth.go
> │   ├── ctypes
> │   │   ├── configurator_iface.go
> │   │   ├── ethash_reward.go
57c59
< │   ├── genesis.go       
---
> │   ├── genesis.go
60c62,63
< │   ├── goethereum       
---
> │   ├── goethereum
> │   │   ├── goethererum_configurator_test.go
62c65,71
< │   │   └── goethereum.go 
---
> │   │   └── goethereum.go
> │   ├── internal
> │   │   └── vars_configurator.go
> │   ├── multigeth
> │   │   ├── chain_config_configurator.go
> │   │   ├── chain_config.go
> │   │   └── chain_config_test.go
71c80
< ├── vars            
---
> ├── vars
73,74c82,83
< │   ├── denomination.go          
< │   ├── network_params.go   
---
> │   ├── denomination.go
> │   ├── network_params.go
76,78c85,87
< └── version.go           
<                   
< 9 directories, 66 files  
---
> └── version.go
> 
> 14 directories, 70 files
```

2019-12-31 20:12 UTC, tzdybal requested changes
I found small issues.

2019-12-31 20:12 UTC, tzdybal commented on consensus/misc/dao.go
> +
Looks like something is missing here ;)

2019-12-31 20:12 UTC, tzdybal commented on consensus/misc/dao.go
> +
Or the other way around, something shouldn't be here ;)

2019-12-31 20:12 UTC, tzdybal commented on params/confp/generic/generic.go
> +	var map1 = make(map[string]interface{})
IMHO `configurator` or `config` or `spec` gives more information than `map1` ;) But it's just a cosmetic issue.

2019-12-31 20:12 UTC, tzdybal commented on params/confp/tconvert/doc.go
> +and then this package can
`[...] die.`

2019-12-31 20:12 UTC, tzdybal commented on params/types/goethereum/goethereum_configurator.go
> +	return ctypes.ConsensusEngineT_Ethash
I assume that `Ethash` is returned instead of `Unknown` because ye-old go-ethereum returns `Ethash` by default, because it has no concept of `Unknown` consensus engine. Am I right?
With this simplification, we don't need first `if` case; following code will be sufficient:
```
	if c.Clique != nil {
		return ctypes.ConsensusEngineT_Clique
	}
	return ctypes.ConsensusEngineT_Ethash
```

2019-12-31 20:12 UTC, tzdybal commented on params/types/internal/vars_configurator.go
> +func One() *GlobalVarsConfigurator {
Why `One`?

2019-12-31 20:12 UTC, tzdybal commented on params/types/internal/vars_configurator.go
> +func (g GlobalVarsConfigurator) GetMaximumExtraDataSize() *uint64 {
Is there any reason why function receiver is of struct type, and not pointer to a struct type?
You can also use `_` instead of `g` to emphasize that it's not used.

2019-12-31 20:12 UTC, tzdybal commented on params/types/internal/vars_configurator.go
> +func (g GlobalVarsConfigurator) SetMaximumExtraDataSize(n *uint64) error {
Why setters accept pointers, when they only need values?

2019-12-31 20:12 UTC, tzdybal commented on params/types/internal/vars_configurator.go
> +func (g GlobalVarsConfigurator) GetMinGasLimit() *uint64 {
Why we're returning pointer if we have to "fake" (ensure it points not into globals) pointer anyways?

2020-01-01 16:35 UTC, meowsbits commented on params/types/internal/vars_configurator.go
> +func (g GlobalVarsConfigurator) SetMaximumExtraDataSize(n *uint64) error {
Because we want to be able to use the concept of "not set" or "undefined" (aka `nil`) in case the value is not set by a config. (This signature is shared by _Transition_ getters and setters, where it's utility is most obvious).

2020-01-01 16:38 UTC, meowsbits commented on params/types/internal/vars_configurator.go
> +func (g GlobalVarsConfigurator) SetMaximumExtraDataSize(n *uint64) error {
Although to your point, without checks for `n == nil` and using the pointer value (`global = *n`) this is either making a silent assumption of just lacks the nil check. Should fix that.

2020-01-01 16:44 UTC, meowsbits commented
@tzdybal Thanks for this feedback, really helpful! 

Since most of it is largely cosmetic or non-structural, non-essential (nothing critically broken and no major objections to general scheme); and the first priority and largest impact of this changeset is refactoring package structure -- I would propose we defer resolution of these points to a subsequent PR. 

This avoids having to rebase all currently stacked subsequent PRs, and allows for these points to be addressed as discrete concerns.

Thoughts?

2020-01-01 17:10 UTC, meowsbits commented on params/confp/generic/generic.go
> +	var map1 = make(map[string]interface{})
This gets resolved in #93

2020-01-02 17:47 UTC, meowsbits commented on params/types/goethereum/goethereum_configurator.go
> +	return ctypes.ConsensusEngineT_Ethash
Fixed in #114

2020-01-02 17:47 UTC, meowsbits commented on params/types/internal/vars_configurator.go
> +func One() *GlobalVarsConfigurator {
Fixed in #114

2020-01-02 17:47 UTC, meowsbits commented on params/types/internal/vars_configurator.go
> +func (g GlobalVarsConfigurator) GetMaximumExtraDataSize() *uint64 {
Fixed in #114

2020-01-02 17:48 UTC, meowsbits commented on params/types/internal/vars_configurator.go
> +func (g GlobalVarsConfigurator) SetMaximumExtraDataSize(n *uint64) error {
See #114

2020-01-02 17:48 UTC, meowsbits commented on params/types/internal/vars_configurator.go
> +func (g GlobalVarsConfigurator) GetMinGasLimit() *uint64 {
See #114

2020-01-02 19:54 UTC, tzdybal approved these changes

2020-01-02 22:10 UTC, merged